FROM node:22-alpine AS deps
WORKDIR /app
RUN corepack enable
COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./
COPY website/package.json ./website/package.json
RUN pnpm install --filter @bifrostnms/website... --frozen-lockfile

FROM deps AS build
COPY website ./website
RUN pnpm --dir website build

FROM node:22-alpine AS runtime
WORKDIR /app/website
ENV NODE_ENV=production
COPY --from=build /app/website/.next/standalone ./
COPY --from=build /app/website/.next/static ./.next/static
EXPOSE 3002
CMD ["node", "server.js"]
