#!/usr/bin/env bash
set -Eeuo pipefail
cd "$(git rev-parse --show-toplevel)"
PYTHONPATH="${PYTHONPATH:-}:$(pwd)/backend"
export PYTHONPATH
exec tortoise -c bifrostnms.database.TORTOISE_ORM makemigrations "$@"
