from collections import Counter
from dataclasses import dataclass
from subprocess import CompletedProcess
from typing import Any

RET: str
QUIT: str
RERUN: str
CHPATH: str

@dataclass(frozen=True)
class Issue:
    code: str
    message: str
    filepath: str
    line: int
    col: int

def _run(cmd: list[str]) -> CompletedProcess[str]: ...
def run_ruff_json(target: str) -> list[dict[str, Any]]: ...
def parse_issues(raw: list[dict[str, Any]]) -> list[Issue]: ...
def group_by_code(
    issues: list[Issue],
) -> tuple[Counter[str], dict[str, str], dict[str, list[Issue]]]: ...
def refresh(
    path: str,
) -> tuple[list[Issue], Counter[str], dict[str, str], dict[str, list[Issue]]]: ...
def format_summary_line(code: str, msg: str, count: int) -> str: ...
def pick_sort_order() -> str | None: ...
def ask_change_path(current_path: str) -> str | None: ...
def pick_rule(counts: Counter[str], first_msg: dict[str, str]) -> str | None: ...
def pick_occurrence(issues: list[Issue]) -> Issue | str | None: ...
def open_in_vscode(issue: Issue) -> None: ...
def show_rule_docs(rule_code: str) -> None: ...
def show_rule_diff_for_path(rule_code: str, path: str) -> None: ...
def show_file_diff_for_rule(rule_code: str, file_path: str) -> None: ...
def show_rule_help(rule_code: str, path: str) -> None: ...
def apply_rule_fix_for_path(rule_code: str, path: str) -> None: ...
def apply_rule_fix_for_file(rule_code: str, file_path: str) -> None: ...
def show_rule_menu(rule_code: str, rule_issues: list[Issue], path: str) -> str: ...
def main() -> None: ...
