#!/usr/bin/env bash
set -e

# Make sure the virtualenv exists, and operate within it.
if [ ! -d venv/bin ]; then
	# shellcheck source=/dev/null
	source /opt/venv/bin/activate
fi

compile_requirements() {
	source="$1"
	output="$2"

	echo "Compiling $output"
	/opt/venv/bin/pip-compile --quiet --resolver=backtracking --allow-unsafe --generate-hashes --no-strip-extras --output-file "$output" "$source"
}

for input in backend/requirements/*.in; do
	output="${input%.in}.txt"
	compile_requirements "$input" "$output"
done
